name         'gsick-luvit'
version      '0.0.1'
source       'https://github.com/gsick/puppet-luvit.git'
author       'Gamaliel Sick'
license      'MIT'
summary      'Luvit and Lum installation module'
description  'Puppet module for installing Luvit and Lum'
project_page 'https://github.com/gsick/puppet-luvit'

dependency   'puppetlabs/stdlib', '>= 4.1.0'
dependency   'pdxcat/singleton', '>= 0.0.5'